name       : git-cola
version    : '3.9'
release    : 21
source     :
    - https://github.com/git-cola/git-cola/archive/v3.9.tar.gz : 66b62f479ad141322351d62aff76e4882719d08f8f29b35f97d30f355391a54e
homepage   : https://git-cola.github.io
license    : GPL-2.0-or-later
component  : programming.tools
summary    : The highly caffeinated Git GUI
description: |
    git-cola is a powerful Git GUI with a slick and intuitive user interface.
builddeps  :
    - pkgconfig(python3)
    - git
    - python3-qt5
rundeps    :
    - git
    - python-qtpy
environment: |
    export GIT_COLA_NO_PRIVATE_LIBS=1 # Prevents install to share/git-cola/lib/cola, prefer site-packages
    export GIT_COLA_NO_VENDOR_LIBS=1 # Don't install vendored qtpy. Use ours.
build      : |
    %make PYTHON=python3
install    : |
    %make_install prefix=/usr PYTHON=python3
    # No, you will not handle every single folder I want to open.
    rm $installdir/usr/share/applications/git-cola-folder-handler.desktop
