name       : git-cola
version    : '3.0'
release    : 10
source     :
    - https://github.com/git-cola/git-cola/archive/v3.0.tar.gz : 61958f998d4618e09ce0dd473411921818d13df838f32102ef5ded984a0d1a50
license    : GPL-2.0
component  : programming.tools
summary    : The highly caffeinated Git GUI
description: |
    The highly caffeinated Git GUI
builddeps  :
    - pkgconfig(python-2.7)
    - git
    - python-qt5
rundeps    :
    - git
    - python-qt5
build      : |
    %make
install    : |
    %make_install prefix=/usr
