name       : git-cola
version    : '2.8'
release    : 3
source     :
    - https://github.com/git-cola/git-cola/archive/v2.8.tar.gz : 9962098bb73c2c13ea32ded01821e447e0c9fbece3d213eaccf6bb02413ccea5
license    : GPL-2.0
component  : programming.tools
summary    : The highly caffeinated Git GUI
description: |
    The highly caffeinated Git GUI
builddeps  :
    - pkgconfig(python-2.7)
    - git
    - python-qt4
rundeps    :
    - git
    - python-qt4
build      : |
    %make
install    : |
    %make_install prefix=/usr
