name       : git-cola
version    : '2.11'
release    : 9
source     :
    - https://github.com/git-cola/git-cola/archive/v2.11.tar.gz : bc4007e0d9c80763ef58d630b033bfdbd8406af77bbd292a6c647ed3ca655b5b
license    : GPL-2.0
component  : programming.tools
summary    : The highly caffeinated Git GUI
description: |
    The highly caffeinated Git GUI
builddeps  :
    - pkgconfig(python-2.7)
    - git
    - python-qt5
rundeps    :
    - git
    - python-qt5
build      : |
    %make
install    : |
    %make_install prefix=/usr
