name       : git-cola
version    : 2.5
release    : 1
source     :
    - https://github.com/git-cola/git-cola/archive/v2.5.tar.gz : 683d4b1c3df094a092f57e1b6439e5bfd1a74f6421792022de96de5039ad7279
license    : GPL-2.0
component  : programming.tools
summary    : The highly caffeinated Git GUI
description: |
    The highly caffeinated Git GUI
builddeps  :
    - pkgconfig(python-2.7)
    - git
    - python-qt4
rundeps    :
    - git
    - python-qt4
build      : |
    %make
install    : |
    %make_install prefix=/usr
