name       : git-cola
version    : 4.2.1
release    : 27
source     :
    - https://github.com/git-cola/git-cola/archive/refs/tags/v4.2.1.tar.gz : 400fed3bac785f7d6c513b19d6a795953367029510ac5dc8b4320864d75cbbac
homepage   : https://git-cola.github.io
license    : GPL-2.0-or-later
component  : programming.tools
summary    : The highly caffeinated Git GUI
description: |
    git-cola is a powerful Git GUI with a slick and intuitive user interface.
networking : yes
builddeps  :
    - pkgconfig(python3)
    - git
    - python-qtpy
    - python3-qt5
rundeps    :
    - git
    - meld
    - python-qtpy
build      : |
    %make
install    : |
    %make_install prefix=/usr PIP=pip3
    # No, you will not handle every single folder I want to open.
    rm $installdir/usr/share/applications/git-cola-folder-handler.desktop
