name       : git-cola
version    : '3.5'
release    : 16
source     :
    - https://github.com/git-cola/git-cola/archive/v3.5.tar.gz : 7fdcfc4326b35e384b97bd4bb2189b4cb5cf258948352759c302e632b41bb2e2
license    : GPL-2.0-or-later
component  : programming.tools
summary    : The highly caffeinated Git GUI
description: |
    The highly caffeinated Git GUI
builddeps  :
    - pkgconfig(python-3.6)
    - git
    - python3-qt5
rundeps    :
    - git
    - python3-qt5
build      : |
    %make
install    : |
    %make_install prefix=/usr
    # No, you will not handle every single folder I want to open.
    rm $installdir/usr/share/applications/git-cola-folder-handler.desktop
