name       : git-cola
version    : '3.1'
release    : 11
source     :
    - https://github.com/git-cola/git-cola/archive/v3.1.tar.gz : a7a083f84697a56ee7c910ccfc680d36c5c447c6b5a3522e01bff9de91474f57
license    : GPL-2.0
component  : programming.tools
summary    : The highly caffeinated Git GUI
description: |
    The highly caffeinated Git GUI
builddeps  :
    - pkgconfig(python-2.7)
    - git
    - python-qt5
rundeps    :
    - git
    - python-qt5
build      : |
    %make
install    : |
    %make_install prefix=/usr
