name       : git-cola
version    : 3.12.0
release    : 26
source     :
    - https://github.com/git-cola/git-cola/archive/refs/tags/v3.12.0.tar.gz : ec1167ea9a472214bf18f5537d96e137c724f3d28a85b3642f07dba35f04b24a
homepage   : https://git-cola.github.io
license    : GPL-2.0-or-later
component  : programming.tools
summary    : The highly caffeinated Git GUI
description: |
    git-cola is a powerful Git GUI with a slick and intuitive user interface.
builddeps  :
    - pkgconfig(python3)
    - git
    - python3-qt5
rundeps    :
    - git
    - python-qtpy
environment: |
    export GIT_COLA_NO_PRIVATE_LIBS=1 # Prevents install to share/git-cola/lib/cola, prefer site-packages
    export GIT_COLA_NO_VENDOR_LIBS=1 # Don't install vendored qtpy. Use ours.
    export PYTHON=python3
build      : |
    %make
install    : |
    %make_install prefix=/usr
    # No, you will not handle every single folder I want to open.
    rm $installdir/usr/share/applications/git-cola-folder-handler.desktop
