name       : git-cola
version    : 2.9.1
release    : 6
source     :
    - https://github.com/git-cola/git-cola/archive/v2.9.1.tar.gz : 41fbd774f43b8d5a5c874e2a6f28a447043ddd40c691f10dfa68d533bed8180a
license    : GPL-2.0
component  : programming.tools
summary    : The highly caffeinated Git GUI
description: |
    The highly caffeinated Git GUI
builddeps  :
    - pkgconfig(python-2.7)
    - git
    - python-qt5
rundeps    :
    - git
    - python-qt5
build      : |
    %make
install    : |
    %make_install prefix=/usr
